//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestNamespace {
    using UnityEngine;
    using System;
    
    
    // This is a test comment
    //on 2 lines
    public class TestType : MonoBehaviour {
        
        private String testField = "Test Generation 5";
        
        private void TestMethod(String testParameter) {
            Debug.Log(testParameter);
        }
        
        private void Start() {
            TestMethod(testField);
        }
    }
}
